### ISSUE TITLE
Cannot find the wgpu binary on linux arm

### ISSUE THREAD

**Issue by ThomasJowett** [eliemichel/sdl2webgpu#10]
I am trying to build your wgpu tutorial project on a linux arm single board computer (https://radxa.com/products/rock5/5b/) but the cmake fetch content does not find the libwgpu_native.a in the _deps folder

`*** No rule to make target '_deps/webgpu-backend-wgpu-static-src/lib/linux-/libwgpu_native.a', needed by 'App/App'. Stop.`

It looks like the cmake script does not append the platform name after the linux-, the path should be _deps/webgpu-backend-wgpu-static-src/lib/linux-aarch64/libwgpu_native.a

I'm not sure where the fetch content script is setting this value?

The code I have is working perfect on all other platforms (linux-x64, macos and windows)

**Comment by eliemichel** [comment]
Hi Thomas! Could you precise which version of the distribution you are using? I indeed didn't have the occasion to check linux-arm, but it is probably an easy fix, sorry for the trouble!

**Comment by ThomasJowett** [comment]
Hi Elie, I am using the fetch content on the main branch of WebGPU-distribution, so I think that is v0.19.4.1
Thanks

**Comment by eliemichel** [comment]
Okey try using the `fetch` branch of the repo, that is going to become the new `main` once I get official binary releases for Dawn (but since you're using wgpu-native it's working well already).

You should then see `lib/libwgpu_native.a` in directory `_deps/wgpu-linux-aarch64-release`.

**Comment by ThomasJowett** [comment]
Thanks, this still didn't work but pointed me in the right direction.

I have made a pull request into the `fetch` branch here: https://github.com/eliemichel/WebGPU-distribution/pull/33

**Comment by eliemichel** [comment]
Merged! Also I just upgraded sdl2webgpu so that it works with latest Dawn, in case you'd need it (though they do not provide linux arm build iirc). Marking as solved then!
