### ISSUE TITLE
SDL3 Support

### ISSUE THREAD

**Issue by sshsphere** [eliemichel/sdl2webgpu#9]
It would be nice if this library was future-proofed for SDL3. (maybe it's better to create a new repo, I don't know)

Main difference is that In SDL3 the `SDL_syswm.h` header has been removed and `SDL_GetWindowWMInfo` is replaced with `SDL_GetWindowProperties`. Also the `SDL_VIDEO_DRIVER_XXXX` macros are deprecated, I guess `SDL_GetCurrentVideoDriver` and `SDL_GetPlatform` can be used instead.
See: [README-migration.md](https://github.com/libsdl-org/SDL/blob/main/docs/README-migration.md#sdl_syswmh)

**Comment by eliemichel** [comment]
I did not reply yet because I did not have the time to work on it, but I still want to say that this is indeed a good idea that I am keeping in the TODOs ;)

**Comment by eliemichel** [comment]
Work in progress here: https://github.com/eliemichel/sdl3webgpu missing support for MSYS for now

**Comment by eliemichel** [comment]
Done.
